import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavbarComponent from "@/components/Navbar";
import { CartProvider } from "@/app/cart/provider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-gray-100 dark:bg-gray-900 text-gray-900 dark:text-gray-100 min-h-screen flex flex-col ${inter.className}`}
      >
        <CartProvider>
          <NavbarComponent />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
